#!/bin/bash
#  _               _
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|

# source global definitions
export PATH=$(getconf PATH)
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ "`id -u`" -eq 0 ]; then
	PS1="[ \[\e[1;31m\]λ\[\e[1;32m\]\[\e[49m\]:\h \W \[\e[0m\]] "
else
	PS1="[ \[\e[1;32m\]λ:\h \W \[\e[0m\]] "
fi

export EDITOR='vim'

# Some aliases
alias kviv='kill $(pidof vivado)'
alias ksdk='kill $(pidof xsdk)'
alias mkd="mkdir -pv"
alias pdf='okular'
alias xclip='xclip -selection c'
alias bigfiles='find -type f -exec du -Sh {} + | sort -rh | head -n 20'
alias scpi='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias sshi='ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias feh='eog'
alias rst2html='rst2html --stylesheet-dirs=~/.rst2html/html --stylesheet=sm-docutils.css'
alias rst2pdf='rst2pdf --stylesheet-path=~/.rst2pdf --stylesheets=rst2pdf.style --use-floating-images'

# Adding color
alias ls='ls -hN --color=auto --group-directories-first'
alias l='ls -hN --color=auto --group-directories-first'
alias ll='ls -lahN --color=auto --group-directories-first'
alias llusb='ls /dev/ttyUSB*'
alias grep='grep --color=auto --exclude=tags --exclude-dir=".svn" --exclude-dir=".git" --line-number'
alias ccat="highlight --out-format=ansi" # Color cat - print file with syntax highlighting.

if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi

# remove duplicate entries in path
if [ -n "$PATH" ]; then
	old_PATH=$PATH:; PATH=
	while [ -n "$old_PATH" ]; do
		x=${old_PATH%%:*}       # the first remaining entry
		case $PATH: in
			*:"$x":*) ;;          # already there
			*) PATH=$PATH:$x;;    # not there yet
		esac
		old_PATH=${old_PATH#*:}
	done
	PATH=${PATH#:}
	unset old_PATH x
fi
