#!/bin/bash
#  _               _
# | |__   __ _ ___| |__  _ __ ___
# | '_ \ / _` / __| '_ \| '__/ __|
# | |_) | (_| \__ \ | | | | | (__
# |_.__/ \__,_|___/_| |_|_|  \___|

# source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

if [ "`id -u`" -eq 0 ]; then
	PS1="[ \[\e[1;31m\]λ\[\e[1;32m\]\[\e[49m\]:\h \W \[\e[0m\]] "
else
	PS1="[ \[\e[1;32m\]λ:\h \W \[\e[0m\]] "
fi

# Some aliases
alias kvivado='kill $(pidof vivado)'
alias mkd="mkdir -pv"
alias pdf='okular'
alias xclip='xclip -selection c'
alias bigfiles='find -type f -exec du -Sh {} + | sort -rh | head -n 20'
alias scpi='scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
alias feh='eog'
alias rst2html='rst2html --stylesheet-dirs=~/.rst2html/html --stylesheet=sm-docutils.css'
alias rst2pdf='rst2pdf --stylesheet-path=~/.rst2pdf --stylesheets=rst2pdf.style --use-floating-images'

# Adding color
alias ls='ls -hN --color=auto --group-directories-first'
alias l='ls -hN --color=auto --group-directories-first'
alias ll='ls -lahN --color=auto --group-directories-first'
alias grep='grep --color=auto --exclude=tags --exclude-dir=".svn" --exclude-dir=".git" --line-number'
alias ccat="highlight --out-format=ansi" # Color cat - print file with syntax highlighting.

# Internet
alias yt="youtube-dl --add-metadata -ic" # Download video link
alias ethspeed="speedometer -r enp12s0"
alias wifispeed="speedometer -r wlp3s0"

# Set path
export stand_path=/bin:/usr/bin:/user/sbin:/usr/local/sbin:/usr/local/bin
export PATH=$stand_path

export SVN_EDITOR='vim'

if [ -f ~/.bash_extended ]; then
	source ~/.bash_extended
fi

if [ -f ~/.bash_aliases ]; then
	source ~/.bash_aliases
fi
