# status bar
set -g status-style bg=colour234,fg=white
setw -g window-status-current-style bg=colour234,fg=yellow

# pane border
set -g pane-border-style fg=colour237
set -g pane-active-border-style fg=colour221

# message text
set -g message-style bg=colour234,fg=brightblue
set -g message-command-style bg=colour234,fg=green

# monitor activity
setw -g monitor-activity on
set -g visual-activity off
setw -g window-status-activity-style bg=colour234,fg=brightblue,bold

# mode colors
set -g mode-style bg=colour67,fg=colour235

set -g window-status-format "#I:#W "
set -g window-status-current-format "#I:#W "

set -g status-interval 2
set -g status-left-length 55
set -g status-right-length 150
set -g status-left '#[fg=blue]#S #[fg=brightblack]•#[default]'
set -g status-right '#22T #[fg=blue]%H:%M#[default]'
