export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="cloud"

plugins=(zsh-autosuggestions z)

source $ZSH/oh-my-zsh.sh

source ~/.commonshellrc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
