export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="cloud"

plugins=(zsh-autosuggestions z)

# Reset zsh-z's tab binding before reload so it doesn't capture itself
(( ${+functions[_zshz_zle_completion_widget]} )) && bindkey '^I' expand-or-complete

source $ZSH/oh-my-zsh.sh

source ~/.commonshellrc

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
