#!/bin/bash

BATTERY=0
BATTERY_INFO=$(acpi -b | grep "Battery ${BATTERY}")
BATTERY_STATE=$(echo "${BATTERY_INFO}" | grep -wo "Full\|Charging\|Discharging")
BATTERY_POWER=$(echo "${BATTERY_INFO}" | grep -o '[0-9]\+%' | tr -d '%')

ICON=""
ICON_BAT_FULL=
ICON_BAT_THREEQUARTERS=
ICON_BAT_HALF=
ICON_BAT_ONEQUARTER=
ICON_BAT_EMPTY=
ICON_BAT_CHARGING=

URGENT_VALUE=10

if [[ $BATTERY_POWER -gt 75 ]]; then
    ICON=$ICON_BAT_FULL
elif [[ $BATTERY_POWER -gt 60 ]]; then
    ICON=$ICON_BAT_THREEQUARTERS
elif [[ $BATTERY_POWER -gt 40 ]]; then
    ICON=$ICON_BAT_HALF
elif [[ $BATTERY_POWER -gt 20 ]]; then
    ICON=$ICON_BAT_ONEQUARTER
else
    ICON=$ICON_BAT_EMPTY
fi

if [[ "${BATTERY_STATE}" = "Charging" ]]; then
  echo "${ICON_BAT_CHARGING} ${BATTERY_POWER}%+"
elif [[ "${BATTERY_STATE}" = "Discharging" ]]; then
  echo "${ICON} ${BATTERY_POWER}%-"
else
  echo "${ICON} ${BATTERY_POWER}%-"
fi

if [[ "${BATTERY_POWER}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi
