#!/bin/bash
# Based on http://openweathermap.org/current
API_KEY="c02c59aaeddb844af9fa994c95a053b3"

# Check on http://openweathermap.org/find
CITY_ID="5346827" # escondido

URGENT_LOWER=50
URGENT_HIGHER=90

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY="" 
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_FAHR="F"

WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=imperial&lang=en"

WEATHER_INFO=$(curl -s "${WEATHER_URL}")
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-zA-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${ICON_SNOW} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${ICON_RAINY} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Thunderstorm* ]]; then
  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${ICON_STORM} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${ICON_CLOUDY} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${ICON_SUNNY} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${ICON_FOG} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
else
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo "${WEATHER_MAIN} ${WEATHER_TEMP}${SYMBOL_FAHR}"
  echo ""
fi

if [[ "${WEATHER_TEMP}" -lt "${URGENT_LOWER}" ]] || [[ "${WEATHER_TEMP}" -gt "${URGENT_HIGHER}" ]]; then
  exit 33
fi
